import gc
import logging
from typing import List, Optional, Tuple, cast

import torch
import transformers
from transformers.tokenization_utils_base import BatchEncoding
from transformers.modeling_outputs import QuestionAnsweringModelOutput
from torch import nn

from attribution.visualization import RichTablePrinter


class LocalQAAttributor():
    device: str
    model: nn.Module
    tokenizer: transformers.PreTrainedTokenizerBase
    embeddings: torch.Tensor

    def __init__(
        self,
        model: nn.Module,
        tokenizer: transformers.PreTrainedTokenizerBase,
        embeddings: torch.Tensor,
        device: Optional[str] = None,
        log_level: int = logging.WARNING,
    ):
        logging.basicConfig(level=log_level)

        if device is None:
            if model.device:
                device = cast(str, model.device.type)
            else:
                device = "cpu"

        logging.info(f"Using device: {device}")
        self.device = device

        self.model = model
        self.embeddings = embeddings
        self.tokenizer = tokenizer

    def get_span_attributions(
        self, question: str, context: str
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        This function calculates the contribution of each token in the input string to the span positions generated by the QA model.

        Parameters:
        input_string (str): The string for which token attributions are to be computed.

        Raises:
        ValueError: If the input_string is not a string, the generation_length is not an integer,
                    the generation_length is not a positive integer, or the model is in training mode.

        Returns:
        Tuple[torch.Tensor, torch.Tensor, torch.Tensor]: First two tensors contain the attribution scores for the span start and end positions and the last tensor contains the token ids.
        """
        self._validate_inputs(self.model, self.tokenizer)

        if self.model.training:
            raise ValueError("Model should be in evaluation mode, not training mode")

        # Tokenize the input string, move to the specified device, and get the input length
        tokenized_input: BatchEncoding = self.tokenizer(question, context, return_tensors="pt").to(self.device)
        token_ids: torch.Tensor = tokenized_input.input_ids
        input_length: int = token_ids.shape[1]

        # Convert input tokens to embeddings with gradients
        input_embeddings = self._get_input_embeddings(self.embeddings, token_ids)
        
        # Compute gradients for the span start logit, retain the graph for the next gradient computation
        output: QuestionAnsweringModelOutput = self.model(inputs_embeds=input_embeddings)
        grad = self._get_gradients(output.start_logits, input_embeddings, retain_graph=True)
        self.model.zero_grad()

        # Compute attribution scores for span start and end positions
        token_ids = token_ids.squeeze()
        attr_scores = self._get_attr_scores(grad, token_ids, input_length)

        # Compute the softmax probabilities for the start and end logits
        span_position_1_probs = torch.softmax(output.start_logits, dim=-1)
        span_position_2_probs = torch.softmax(output.end_logits, dim=-1)

        span_position_1_idx = torch.argmax(span_position_1_probs, dim=-1)
        span_position_2_idx = torch.argmax(span_position_2_probs, dim=-1)

        if span_position_1_idx < span_position_2_idx:
            span_probs = torch.cat((span_position_1_probs, span_position_2_probs), dim=0)
            span_indices = torch.tensor([span_position_1_idx, span_position_2_idx])
        else:
            span_probs = torch.cat((span_position_2_probs, span_position_1_probs), dim=0)
            span_indices = torch.tensor([span_position_2_idx, span_position_1_idx])

        # Return both start and end attribution scores along with the token ids
        return attr_scores, token_ids, span_probs, span_indices

    def print_attributions(
        self,
        word_list: List[str],
        attr_scores: torch.Tensor,
        token_ids: torch.Tensor,
    ):
        """
        This function prints the attribution scores of each token in a formatted table.

        Parameters:
            word_list (List[str]): The list of words for which attributions are computed.
            attr_scores (torch.Tensor): The tensor containing the attribution scores for each token.
            token_ids (torch.Tensor): The tensor containing the ids of the tokens.
        """
        max_abs_attr_val = attr_scores.abs().max().item()
        table_printer = RichTablePrinter(max_abs_attr_val)
        attr_scores = attr_scores.unsqueeze(dim=0)

        table_printer.print_attribution_table(word_list, attr_scores, token_ids, 0)

    def cleanup(self) -> None:
        """
        This function is used to free up the memory resources. It clears the GPU cache and triggers garbage collection.

        Returns:
        None
        """
        if hasattr(torch, self.device) and hasattr(getattr(torch, self.device), "empty_cache"):
            logging.info(f"Clearing {self.device} cache")
            getattr(torch, self.device).empty_cache()
        gc.collect()

    def _get_input_embeddings(
        self, embeddings: torch.Tensor, token_ids: torch.Tensor
    ) -> torch.Tensor:
        input_embeddings = embeddings[token_ids]
        return torch.nn.Parameter(input_embeddings, requires_grad=True)

    def _generate_tokens(
        self,
        model: nn.Module,
        token_ids: torch.Tensor,
    ):
        with torch.no_grad():
            gen_tokens = model.generate(
                token_ids.unsqueeze(0),
                max_new_tokens=1,
            )
        next_token_id = gen_tokens[0][-1]
        return gen_tokens, next_token_id

    def _get_gradients(
        self,
        logits: torch.Tensor,
        input_embeddings: torch.Tensor,
        retain_graph: bool = False
    ) -> torch.Tensor:
        """
        This function computes the gradients associated with the input embeddings with respect to the specified output logits.
        """
        probs = torch.softmax(logits, dim=-1)
        # Assume we are interested in the max logit (the predicted start or end token position)
        max_logit_idx = probs.argmax(dim=-1)
        selected_logit = logits[0, max_logit_idx]

        # Compute gradients
        selected_logit.backward(retain_graph=retain_graph)

        if input_embeddings.grad is None:
            raise ValueError("Input embeddings gradient is None.")

        return input_embeddings.grad.squeeze()

    def _get_attr_scores(
        self, grad: torch.Tensor, token_ids: torch.Tensor, input_length: int
    ) -> torch.Tensor:
        """
        This function computes the attribution scores from the gradients.
        """

        attr_scores = torch.zeros(input_length)
        for i, _ in enumerate(token_ids):
            presence_grad = grad[i].norm(p=1)
            attr_scores[i] = presence_grad
        return attr_scores

    def _validate_inputs(
        self,
        model: nn.Module,
        tokenizer: transformers.PreTrainedTokenizerBase
    ):
        # Check if model is a valid torch module
        if not isinstance(model, torch.nn.Module):
            raise ValueError(
                "Model must be an instance of a class that inherits from torch.nn.Module"
            )

        # Check if model is in evaluation mode
        if model.training:
            raise ValueError("Model should be in evaluation mode, not training mode")

        # Check if tokenizer is callable
        if not callable(tokenizer):
            raise ValueError("Tokenizer must be callable")
